name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Tidy & vet
        run: |
          go mod tidy -v
          go vet ./...
      - name: Build
        run: go build ./...
      - name: Smoke-run (1 s)
        run: |
          go run . -testmode || true
